apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders-ms-spring
  labels:
    app: "orders-ms-spring"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "orders-ms-spring"
    spec:
      initContainers:
      - name: test-mariadb
        image: bitnami/mariadb:10.1.38
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        - "-c"
        - "until mysql -h ${MYSQL_HOST} -P ${MYSQL_PORT} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e status; do echo waiting for mariadb; sleep 1; done"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: MYSQL_HOST
          value: "orders-mariadb"
        - name: MYSQL_PORT
          value: "3307"
        - name: MYSQL_DATABASE
          value: "ordersdb"
        - name: MYSQL_USER
          value: "dbuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-mariadb-secret
              key: mariadb-password
      containers:
      - name: "orders-ms-spring"
        image: __IMAGE__
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /spring-tmp
          name: spring-tmp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /micro/actuator/health
            port: 8090
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /micro/actuator/liveness
            port: 8090
          initialDelaySeconds: 35
          periodSeconds: 20
          failureThreshold: 6
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: JAVA_TMP_DIR
          value: /spring-tmp
        - name: MYSQL_HOST
          value: "orders-mariadb"
        - name: MYSQL_PORT
          value: "3307"
        - name: MYSQL_DATABASE
          value: "ordersdb"
        - name: MYSQL_USER
          value: "dbuser"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orders-mariadb-secret
              key: mariadb-password
        - name: HS256_KEY
          value: "E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a"
      volumes:
      - name: spring-tmp
        emptyDir:
          medium: "Memory"
