apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-ms-spring
  labels:
    app: "customer-ms-spring"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "customer-ms-spring"
    spec:
      initContainers:
      - name: test-couchdb
        image: ibmcase/bluecompute-bash-curl-ssl:latest
        imagePullPolicy:
        command:
        - "/bin/bash"
        - "-c"
        - "until curl --max-time 1 ${COUCHDB_PROTOCOL}://${COUCHDB_USERNAME}:${COUCHDB_PASSWORD}@${COUCHDB_HOST}:${COUCHDB_PORT}; do echo waiting for couchdb; /bin/sleep 1; done"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: COUCHDB_HOST
          value: "customer-couchdb-svc-couchdb"
        - name: COUCHDB_PROTOCOL
          value: "http"
        - name: COUCHDB_PORT
          value: "5985"
        - name: COUCHDB_DATABASE
          value: "customers"
        - name: COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-couchdb-couchdb
              key: adminUsername
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-couchdb-couchdb
              key: adminPassword
      containers:
      - name: "customer-ms-spring"
        image: __IMAGE__
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /spring-tmp
          name: spring-tmp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /micro/actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /micro/actuator/liveness
            port: 8080
          initialDelaySeconds: 35
          periodSeconds: 20
          failureThreshold: 6
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: JAVA_TMP_DIR
          value: /spring-tmp
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-couchdb-couchdb
              key: adminPassword
        - name: COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-couchdb-couchdb
              key: adminUsername
        - name: COUCHDB_PROTOCOL
          value: http
        - name: COUCHDB_HOST
          value: customer-couchdb-svc-couchdb
        - name: COUCHDB_PORT
          value: 5985
        - name: COUCHDB_DATABASE
          value: customers
        - name: COUCHDB_HS256_KEY
          value: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a
      volumes:
      - name: spring-tmp
        emptyDir:
          medium: "Memory"
