apiVersion: batch/v1
kind: Job
metadata:
  name: customer-ms-spring-create-user-hw3sv
  labels:
    app: "customer-ms-spring"
spec:
  template:
    metadata:
      name: customer-ms-spring-create-user-sg7zf
      labels:
        app: "customer-ms-spring"
    spec:
      restartPolicy: Never
      initContainers:
      - name: test-customer-ms-spring
        image: ibmcase/bluecompute-bash-curl-ssl:latest
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        - "-c"
        - "until curl --max-time 1 http://customer-ms-spring:8080; do echo waiting for customer-ms-spring; sleep 1; done"
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: COUCHDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: customer-couchdb-couchdb
              key: adminPassword
        - name: COUCHDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: customer-couchdb-couchdb
              key: adminUsername
        - name: COUCHDB_PROTOCOL
          value: http
        - name: COUCHDB_HOST
          value: customer-couchdb-svc-couchdb
        - name: COUCHDB_PORT
          value: 5985
        - name: COUCHDB_DATABASE
          value: customers
        - name: COUCHDB_HS256_KEY
          value: E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a
      containers:
      - name: create-user
        image: ibmcase/bluecompute-bash-curl-ssl:latest
        command: ["/bin/bash", "-c" ]
        args:
        - >
            secret=${HS256_KEY};
            jwt1=$(echo -n '{"alg":"HS256","typ":"JWT"}' | openssl enc -base64);
            jwt2=$(echo -n "{\"scope\":[\"admin\"],\"user_name\":\"${TEST_USER}\"}" | openssl enc -base64);
            jwt3=$(echo -n "${jwt1}.${jwt2}" | tr '+\/' '-_' | tr -d '=' | tr -d '\r\n');
            jwt4=$(echo -n "${jwt3}" | openssl dgst -binary -sha256 -hmac "${secret}" | openssl enc -base64 | tr '+\/' '-_' | tr -d '=' | tr -d '\r\n');
            jwt=$(echo -n "${jwt3}.${jwt4}");
            for i in `seq 1 120`; do
              curl --max-time 5 -X POST http://customer-ms-spring:8080/micro/customer -H "Content-type: application/json" -H "Authorization: Bearer ${jwt}" -d "{\"username\": \"${TEST_USER}\", \"password\": \"${TEST_PASSWORD}\", \"firstName\": \"foo\", \"lastName\": \"bar\", \"email\": \"foo@bar.com\"}";
            done
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 384Mi
          requests:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 2000
        env:
        - name: TEST_USER
          value: "foo"
        - name: TEST_PASSWORD
          value: "bar"
        - name: HS256_KEY
          value: "E6526VJkKYhyTFRFMC0pTECpHcZ7TGcq8pKsVVgz9KtESVpheEO284qKzfzg8HpWNBPeHOxNGlyudUHi6i8tFQJXC8PiI48RUpMh23vPDLGD35pCM0417gf58z5xlmRNii56fwRCmIhhV7hDsm3KO2jRv4EBVz7HrYbzFeqI45CaStkMYNipzSm2duuer7zRdMjEKIdqsby0JfpQpykHmC5L6hxkX0BT7XWqztTr6xHCwqst26O0g8r7bXSYjp4a"
