apiVersion: v1
kind: Service
metadata:
  name: catalog-ms-spring
  labels:
    app: "catalog-ms-spring"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: "catalog-ms-spring"
