apiVersion: v1
kind: Service
metadata:
  name: auth-ms-spring
  labels:
    app: "auth-ms-spring"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: "auth-ms-spring"
