apiVersion: v1
kind: Service
metadata:
  name: orders-ms-spring
  labels:
    app: "orders-ms-spring"
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: "orders-ms-spring"
